# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcdb42b294ef2206b4eea9ed7125b375e2a84e1c0e01223612337cdac569cd886f075f624b7e89b0489ddc2ab5e870946d0ba2f85ead0995fa7605aa252e4bfc

test:
  secret_key_base: e66782c4b16529dbb033d4496d89b1186020581e2959992839e948435ef656ae19fc76592677340c9c1705edd42580124e7c56acf08dff6320f2c4bb1526a3be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
